# -*- Mode: Makefile; -*-
#
# See COPYRIGHT in top-level directory.
#

CC=cc
CFLAGS= -O0 -g -Wall -Wno-stringop-overflow
BINS=simple deadlock split memory_debugging

all: $(BINS)

clean:
	rm -f $(BINS)
